tables:
    - name: member
      rows: 1000
      columns:
        - name: id
          value: ${uuid}
        - name: email
          value: ${email}
        - name: registered
          range: timestamp
          props:
            min: 2014-07-15T01:00:00+01:00
            max: 2024-07-12T01:00:00+01:00
            format: "2006-01-02T15:04:05Z"
    - name: product
      rows: 1000
      columns:
        - name: id
          value: ${uuid}
        - name: name
          value: ${name}
        - name: price
          range: float
          props:
            min: 1
            max: 1000
    - name: purchase
      rows: 10000
      columns:
        - name: id
          value: ${uuid}
        - name: member_id
          ref: member.id
        - name: amount
          range: float
          props:
            min: 1
            max: 1000
        - name: status
          set:
            - pending
            - paid
            - dispatched
        - name: ts
          range: timestamp
          props:
            min: 2014-07-15T01:00:00+01:00
            max: 2024-07-12T01:00:00+01:00
            format: "2006-01-02T15:04:05Z"
    - name: purchase_line
      rows: 100000
      columns:
        - name: id
          value: ${uuid}
        - name: purchase_id
          ref: purchase.id
        - name: product_id
          ref: product.id
        - name: quantity
          range: int
          props:
            min: 1
            max: 1000000
