tables:
  - name: users
    rows: 100000
    columns:
      - name: id
        value: ${uuid}
      - name: email
        value: ${email}
      - name: full_name
        value: ${name}
      - name: location
        range: point
        props:
          lat: 51.04284752235447
          lon: -0.8911379425829405
          distance_km: 100